### ISSUE TITLE
Build fails with missing dependencies - 

### ISSUE THREAD

**Issue by thomasgpeters** [beached/json_to_cpp#6]
Missing dependencies.  I can't build json_to_cpp bacause I am unable to identiry the following. 

find_package(date REQUIRED)
find_package(fmt REQUIRED)

Hi Darrell, these both seem a bit obscure.  Can you refer me to these packages?  I am trying to build in my macos and have boost 10.85.0 installed.  Is there some reason you froze the boot version to 1.60.0.

Thanks so much...
Thomas

**Comment by beached** [comment]
They are listed in https://github.com/beached/json_to_cpp/blob/master/vcpkg.json .  So using vcpkg makes it simpler and can be done by adding `-DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake` in your cmake invocation.  Otherwise 
Boost
fmtlib
howardhinnant/date 
will need to be available
